name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android
            id: android
            target: Android
    
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
